-- begin SERVICES_REPAIR
alter table SERVICES_REPAIR add constraint FK_SERVICES_REPAIR_CENTER foreign key (CENTER_ID) references SERVICES_CAR_SERVICE_CENTER(ID)^
alter table SERVICES_REPAIR add constraint FK_SERVICES_REPAIR_EMPLOYEE foreign key (EMPLOYEE_ID) references SERVICES_EMPLOYEE(ID)^
create index IDX_SERVICES_REPAIR_CENTER on SERVICES_REPAIR (CENTER_ID)^
create index IDX_SERVICES_REPAIR_EMPLOYEE on SERVICES_REPAIR (EMPLOYEE_ID)^
-- end SERVICES_REPAIR
-- begin SERVICES_CAR_SERVICE_CENTER
alter table SERVICES_CAR_SERVICE_CENTER add constraint FK_SERVICES_CAR_SERVICE_CENTER_CITY foreign key (CITY_ID) references SERVICES_CITY(ID)^
create index IDX_SERVICES_CAR_SERVICE_CENTER_CITY on SERVICES_CAR_SERVICE_CENTER (CITY_ID)^
-- end SERVICES_CAR_SERVICE_CENTER
-- begin SERVICES_EMPLOYEE
alter table SERVICES_EMPLOYEE add constraint FK_SERVICES_EMPLOYEE_CENTER foreign key (CENTER_ID) references SERVICES_CAR_SERVICE_CENTER(ID)^
create index IDX_SERVICES_EMPLOYEE_CENTER on SERVICES_EMPLOYEE (CENTER_ID)^
-- end SERVICES_EMPLOYEE
-- begin SERVICES_CUSTOMER_SERVICE
alter table SERVICES_CUSTOMER_SERVICE add constraint FK_SERVICES_CUSTOMER_SERVICE_CUSTOMER foreign key (CUSTOMER_ID) references SERVICES_CUSTOMER(ID)^
alter table SERVICES_CUSTOMER_SERVICE add constraint FK_SERVICES_CUSTOMER_SERVICE_CAR_SERVICE_CENTER foreign key (CAR_SERVICE_CENTER_ID) references SERVICES_CAR_SERVICE_CENTER(ID)^
create index IDX_SERVICES_CUSTOMER_SERVICE_CUSTOMER on SERVICES_CUSTOMER_SERVICE (CUSTOMER_ID)^
create index IDX_SERVICES_CUSTOMER_SERVICE_CAR_SERVICE_CENTER on SERVICES_CUSTOMER_SERVICE (CAR_SERVICE_CENTER_ID)^
-- end SERVICES_CUSTOMER_SERVICE
-- begin SERVICES_INDIVIDUAL
alter table SERVICES_INDIVIDUAL add constraint FK_SERVICES_INDIVIDUAL_INDIVIDUAL foreign key (INDIVIDUAL_ID) references SERVICES_CUSTOMER(ID)^
-- end SERVICES_INDIVIDUAL
